name: flutter_gen
description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 5.4.0
homepage: https://github.com/FlutterGen/flutter_gen
repository: https://github.com/FlutterGen/flutter_gen
documentation: https://github.com/FlutterGen/flutter_gen
issue_tracker: https://github.com/FlutterGen/flutter_gen/issues
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'

executables:
  fluttergen: flutter_gen_command

dependencies:
  flutter_gen_core:
    git:
      url: https://github.com/vm-px/flutter_gen
      path: packages/core
      ref: vector_graphics_support
  args: ^2.0.0

dev_dependencies:
  lints: any # Ignoring the version to allow editing across SDK versions.
  test: ^1.16.0
  test_process: ^2.0.0
